set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(JETSON_ROOT_PATH /opt/Linux_for_Tegra_64_tx1/rootfs)
set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)
set(CMAKE_CUDA_HOST_COMPILER /usr/bin/aarch64-linux-gnu-g++ CACHE FILEPATH "nvcc host compiler" FORCE)

include_directories(SYSTEM ${JETSON_ROOT_PATH}/usr/include)

set(CMAKE_SYSROOT ${JETSON_ROOT_PATH})

set(CMAKE_FIND_ROOT_PATH "${JETSON_ROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

